#ifndef FORTRAN_MONGO_CONST_H
#define FORTRAN_MONGO_CONST_H

#define FORTRAN_MONGO_NO_ERROR 0
#define FORTRAN_MONGO_MEMORY_ERROR 1
#define FORTRAN_MONGO_URI_NEW_ERROR 2
#define FORTRAN_MONGO_CLIENT_NEW_ERROR 3
#define FORTRAN_MONGO_BAD_DB_ID 4
#define FORTRAN_MONGO_BAD_QUERY 5
#define FORTRAN_MONGO_BAD_CURSOR 6
#define FORTRAN_MONGO_BSON_NEW_ERROR 7
#define FORTRAN_MONGO_INSERT_ERROR 8

#endif
